In [1]:
from sklearn import datasets
from sklearn import svm
import numpy as np
import pandas as pd

In [2]:
iris = datasets.load_iris()

In [3]:
clf = svm.SVC(gamma=0.001, C=100.)
clf.fit(iris.data[:-1], iris.target[:-1])  

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [4]:
clf.predict(iris.data[-1:])

array([2])

In [5]:
df = pd.DataFrame(data=np.c_[iris['data'], iris['target']],
                     columns= iris['feature_names'] + ['target'])
input_df = pd.DataFrame(data=iris['data'], columns = iris['feature_names'])
output_df = pd.DataFrame(data=iris['target'], columns = ['target'])

In [6]:
pd.concat([input_df, output_df], axis=1, join='inner')

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
5                  5.4               3.9                1.7               0.4   
6                  4.6               3.4                1.4               0.3   
7                  5.0               3.4                1.5               0.2   
8                  4.4               2.9                1.4               0.2   
9                  4.9               3.1                1.5               0.1   
10                 5.4               3.7                1.5               0.2   
11                 4.8               3.4                1.6               0.2   
12                 4.8               3.0                1.4               0.1   
13                 4.3               3.0                1.1               0.1   
14                 5.8               4.0                1.2               0.2   
15                 5.7               4.4                1.5               0.4   
16                 5.4               3.9                1.3               0.4   
17                 5.1               3.5                1.4               0.3   
18                 5.7               3.8                1.7               0.3   
19                 5.1               3.8                1.5               0.3   
20                 5.4               3.4                1.7               0.2   
21                 5.1               3.7                1.5               0.4   
22                 4.6               3.6                1.0               0.2   
23                 5.1               3.3                1.7               0.5   
24                 4.8               3.4                1.9               0.2   
25                 5.0               3.0                1.6               0.2   
26                 5.0               3.4                1.6               0.4   
27                 5.2               3.5                1.5               0.2   
28                 5.2               3.4                1.4               0.2   
29                 4.7               3.2                1.6               0.2   
..                 ...               ...                ...               ...   
120                6.9               3.2                5.7               2.3   
121                5.6               2.8                4.9               2.0   
122                7.7               2.8                6.7               2.0   
123                6.3               2.7                4.9               1.8   
124                6.7               3.3                5.7               2.1   
125                7.2               3.2                6.0               1.8   
126                6.2               2.8                4.8               1.8   
127                6.1               3.0                4.9               1.8   
128                6.4               2.8                5.6               2.1   
129                7.2               3.0                5.8               1.6   
130                7.4               2.8                6.1               1.9   
131                7.9               3.8                6.4               2.0   
132                6.4               2.8                5.6               2.2   
133                6.3               2.8                5.1               1.5   
134                6.1               2.6                5.6               1.4   
135                7.7               3.0                6.1               2.3   
136                6.3               3.4                5.6               2.4   
137                6.4              

In [7]:
iris.data[:2]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2]])

In [11]:
from sklearn.externals import joblib
import json

joblib.dump(clf, '../models/svm/model.pkl')
incols = list(input_df.columns)
outcols = list(output_df.columns)
metadata = {}
metadata['model'] = type(clf).__name__
metadata['inputs'] = incols
metadata['outputs'] = outcols
with open('../models/svm/metadata.json', 'w') as fp:
    json.dump(metadata, fp)

array([1, 2, 3, 4, 5])

In [37]:
cols = list(input_df)
for row in input_df.iterrows():
    for col in cols:
        print("{0}:{1}".format(col, row[1][col]))
    

sepal length (cm):5.1
sepal width (cm):3.5
petal length (cm):1.4
petal width (cm):0.2
sepal length (cm):4.9
sepal width (cm):3.0
petal length (cm):1.4
petal width (cm):0.2
sepal length (cm):4.7
sepal width (cm):3.2
petal length (cm):1.3
petal width (cm):0.2
sepal length (cm):4.6
sepal width (cm):3.1
petal length (cm):1.5
petal width (cm):0.2
sepal length (cm):5.0
sepal width (cm):3.6
petal length (cm):1.4
petal width (cm):0.2
sepal length (cm):5.4
sepal width (cm):3.9
petal length (cm):1.7
petal width (cm):0.4
sepal length (cm):4.6
sepal width (cm):3.4
petal length (cm):1.4
petal width (cm):0.3
sepal length (cm):5.0
sepal width (cm):3.4
petal length (cm):1.5
petal width (cm):0.2
sepal length (cm):4.4
sepal width (cm):2.9
petal length (cm):1.4
petal width (cm):0.2
sepal length (cm):4.9
sepal width (cm):3.1
petal length (cm):1.5
petal width (cm):0.1
sepal length (cm):5.4
sepal width (cm):3.7
petal length (cm):1.5
petal width (cm):0.2
sepal length (cm):4.8
sepal width (cm):3.4
petal lengt